version: '2'
services:
  site:
    image: repo.treescale.com/ultravisual/ultravisual-site:latest
    # image: ultravisual-site:test
    ports:
      - "3000:3000"
    container_name: ultravisual.site

  nginx:
    image: repo.treescale.com/ultravisual/ultravisual-nginx:0.0.1
    # image: ultravisual-nginx:test
    ports:
      - "80:80"
    container_name: ultravisual.nginx
    depends_on:
      - site
